export const businessPartnerRoleTypes = [
    { code: "ZLM001", value: "Promoter"},
    { code: "ZLM002", value: "Lenders Financial Advisor"},
    { code: "ZLM003", value: "Lenders Engineer"},
    { code: "ZLM004", value: "Lenders Insurance Advisor"},
    { code: "ZLM005", value: "Security Trustee"},
    { code: "ZLM006", value: "Legal Counsel"},
    { code: "ZLM007", value: "Loan underwriter"},
    { code: "ZLM008", value: "Syndicate Partner"},
    { code: "ZLM009", value: "Co-Security Trustee"},
    { code: "ZLM010", value: "Co-Appraisal Officer"},
    { code: "ZLM011", value: "TRA Banker"},
    { code: "ZLM012", value: "Consultant"},
    { code: "ZLM013", value: "Appraisal Officer"},
    { code: "ZLM014", value: "PFS Relationship officer"},
    { code: "ZLM015", value: "EPC contractor"},
    { code: "ZLM016", value: "Co-Lender"},
    { code: "ZLM017", value: "Customer-Empl(Supp&3rd Pa"},
    { code: "ZLM018", value: "Nodal Officer-Legal"},
    { code: "ZLM019", value: "Nodal Officer-Disb&Recov"},
    { code: "ZLM020", value: "Lead Bank"},
    { code: "ZLM021", value: "Employee(SuppServ&3rd pa)"},
    { code: "ZLM022", value: "Loan DocumentationOfficer"},
    { code: "ZLM023", value: "PFS IT Team"},
    { code: "ZLM024", value: "Nodal Officer-Monitoring"},
    { code: "ZLM025", value: "Key Promoter"},
    { code: "ZLM026", value: "Group Company"},
    { code: "ZLM027", value: "Technology Provider"},
    { code: "TR0100", value: "Main Loan Partner"},
    { code: "TR0101", value: "Co-Borrower"},
    { code: "TR0110", value: "Prospect"},
    { code: "TR0113", value: "Credit Standing Check"},
    { code: "TR0115", value: "Special Arrangement"},
    { code: "TR0120", value: "Cust. Authorized Drawer"},
    { code: "TR0121", value: "Other Loan Partner"},
    { code: "TR0150", value: "Issuer"},
    { code: "TR0151", value: "Counterparty"},
    { code: "TR0152", value: "Depository Bank"},
    { code: "TR0153", value: "Paying Bank"},
    { code: "TR0154", value: "Beneficiary"},
    { code: "TR0160", value: "Ultimate Borrower"},
    { code: "TR0200", value: "Guarantor"},
    { code: "TR0202", value: "Alternative Payer"},
    { code: "TR0203", value: "Collector"},
    { code: "TR0600", value: "Master Tenant w.Cust.Acct"},
    { code: "TR0601", value: "Tenant (w/o Cust.Account)"},
    { code: "TR0602", value: "Landlord w.Vendor Account"},
    { code: "TR0603", value: "Partner w. Customer Acct"},
    { code: "TR0604", value: "Partner w. Vendor Account"},
    { code: "TR0605", value: "Owner (Customer)"},
    { code: "TR0606", value: "Manager w. Vendor Acct"},
    { code: "TR0610", value: "Tenant Ext.Compar.Apartmt"},
    { code: "TR0622", value: "Subsidizer"},
    { code: "TR0624", value: "Subsidizer (w.Cust.Acct)"},
    { code: "TR0630", value: "Court"},
    { code: "TR0635", value: "State Central Bank"},
    { code: "TR0636", value: "Bank for Rent Deposit"},
    { code: "TR0640", value: "Applicant"},
    { code: "TR0641", value: "Co-Applicant"},
    { code: "TR0645", value: "Authorized Occupant"},
    { code: "TR0646", value: "Auth. to Suggest Tenant"},
    { code: "TR0655", value: "Guarantor"},
    { code: "TR0700", value: "Policyholder"},
    { code: "TR0701", value: "Insurer"},
    { code: "TR0702", value: "Person Insured"},
    { code: "TR0703", value: "Bank"},
    { code: "TR0704", value: "Insurance Tracking Vendor"},
    { code: "TR0705", value: "Payer"},
    { code: "TR0706", value: "Insurance Company Agent"},
    { code: "TR0800", value: "Owner"},
    { code: "TR0801", value: "Broker"},
    { code: "TR0802", value: "Notary"},
    { code: "TR0803", value: "Property Developer"},
    { code: "TR0804", value: "Primary Contractor"},
    { code: "TR0805", value: "Primary Receiver"},
    { code: "TR0806", value: "Administrator"},
    { code: "TR0807", value: "Technology"},
    { code: "TR0808", value: "Janitor"},
    { code: "TR0809", value: "Architect"},
    { code: "TR0810", value: "Land Registry"},
    { code: "TR0811", value: "Legal Owner"},
    { code: "TR0812", value: "Land Lease Right Holder"},
    { code: "TR0815", value: "Appraiser"},
    { code: "TR0820", value: "Survey Office"},
    { code: "TR0821", value: "Tax Office"},
    { code: "TR0822", value: "Creditor"},
    { code: "TR0823", value: "Holder"},
    { code: "TR0824", value: "Obligated Party"},
    { code: "TR0825", value: "Special Role"},
    { code: "TR0850", value: "Corresp. Partner (priv.)"},
    { code: "TR0860", value: "Corresp. Partner (Bus.)"},
    { code: "TR0990", value: "Loan Contract Officer"},
    { code: "TR0991", value: "Loan Rollover Officer"},
    { code: "TR0992", value: "Loan Accounting Officer"},
    { code: "TR0995", value: "Loans Officer"},
    { code: "TR0997", value: "SCS Clerk"},
    { code: "TR0998", value: "Loans Administrator"}
]